# Generated by Django 4.2.3 on 2023-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Имя")),
                ("date_of_birth", models.DateField(verbose_name="Дата рождения")),
                (
                    "phone_number",
                    models.CharField(max_length=64, verbose_name="Номер телефона"),
                ),
            ],
            options={
                "verbose_name": "form",
                "verbose_name_plural": "forms",
            },
        ),
    ]
