# Generated by Django 4.2.3 on 2023-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Заголовок")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "preview_url",
                    models.URLField(
                        blank=True, max_length=256, null=True, verbose_name="Картинка"
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "news",
                "verbose_name_plural": "news",
            },
        ),
    ]
